TRACES_DIR = "traces"
TRACES_PREPROCESSED_DIR = "traces_preprocessed"

LINE_COLOR = (0, 0, 0)
LINE_THICKNESS = 6
NO_HAND_FRAMES_THRESHOLD = 10

PREPROCESS_OUTPUT_SIZE = (28, 28)
PREPROCESS_PADDING_RATIO = 0.1

MIN_DETECTION_CONFIDENCE = 0.6
MIN_TRACKING_CONFIDENCE = 0.6
MAX_NUM_HANDS = 1

CAMERA_INDEX = 0

